import React from 'react'
import Head  from 'next/head'
import Image from 'next/image'
import styles from '../styles/Nav.module.css'

const Nav = () => {
  return (
    <>
        <Head>
        <title>Pet Fish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
        </Head>

        <nav className={styles.container}>
            <div className={styles.navContainer}>
                <div className={styles.colNav}>
                    <Image src="/icons/fish.png" alt="Fish" width={60} height={25} priority/>
                    <h1><a href="#">PetFish</a></h1>
                </div>
                <div className={styles.colNav}>
                    <button className={styles.cartButton}><span class="material-icons">shopping_cart</span>t</button>
                </div>
            </div>
        </nav>
    </>
  )
}

export default Nav
